id = "spip"
name = "SPIP"
version = "0.1.0"
schema_version = 1
authors = ["Mathieu Alphamosa"]
description = "Support du langage de squelettes SPIP (CMS) pour Zed : coloration syntaxique, snippets et complétions"
repository = "https://github.com/MathieuAlphamosa/zed-spip"
snippets = "./snippets/spip.json"

[grammars.spip]
repository = "https://github.com/MathieuAlphamosa/tree-sitter-spip"
rev = "9dba7fc631285c2598427d7ced4ae9fefcc3260d"
