id = "spip"
name = "SPIP"
version = "0.1.0"
schema_version = 1
authors = ["Mathieu Alphamosa"]
description = "Support du langage de squelettes SPIP (CMS) pour Zed : coloration syntaxique, snippets et complétions"
repository = "https://github.com/MathieuAlphamosa/zed-spip"

[grammars.spip]
repository = "https://github.com/MathieuAlphamosa/tree-sitter-spip"
rev = "4c634230b0ae9a0f91fdae04c667aa526d5c90ff"
